import { db } from "@/server/db";
import { eq } from "drizzle-orm";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { domain: string };
}) {
  const domain = params.domain.split(".")[0] ?? "home";

  if (domain === "home") return <div>This is home domain</div>;

  const res = await db.query.sites.findFirst({
    where: (sites) => eq(sites.name, domain),
  });

  if (!res) return <div>there is no such marketplace</div>;

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
